### ISSUE TITLE
A credit was expected

### ISSUE THREAD

**Issue by emadeldeen24** [oezyurty/CLUDA#1]
It seems that your [baselines](https://github.com/oezyurty/CLUDA/blob/main/main/algorithms.py) are completely adopted from our [AdaTime work](https://github.com/emadeldeen24/AdaTime), however, I can't find any credit to our work on this github repo or on your [ICLR submission](https://openreview.net/forum?id=xPkJYRsQGM). I understand that the codes are public, but I think you should at least give the expected credit to the authors, even from an ethical perspective.

**Comment by oezyurty** [comment]
Hi Dear @emadeldeen24, 

Thank you so much for creating the issue! You are right that some of the baseline implementations are adopted from your work. Please accept our apologies for not adequately citing your new AdaTime work. 

Please check our updated README, where we refer to your AdaTime framework regarding the baseline implementations. In the next revision of the paper, which will happen soon, you will find the appropriate citation of the corresponding paper in all the platforms. 

Of note, you can already find your earlier work [TS-TCC](https://arxiv.org/pdf/2106.14112.pdf) cited in the related work. 

We are deeply sorry for any inconvenience that it may cause. Please reopen the issue if you have any further feedbacks, which we would be glad to hear.
