### ISSUE TITLE
Question about the MIMIC-IV data input

### ISSUE THREAD

**Issue by xinyuejohn** [oezyurty/CLUDA#7]
Hi, thanks for your amazing work, nice implementations and especially the detailed documentation! 

I want to run your code using MIMIC-IV dataset but I had my own data preprocessing pipeline. 
could you please tell me 
1) if my data input format is correct and if I have correct settings? 
2) if I can run your cluda network without using mask. 

Here's the my data format right now:
```
timeseries.npy: shape of N*L*C, 
static.npy: shape of N*C_2
mortality.npy: shape of N

where N is number of patients, L is length of observation window (48h), C is number of features.
```
Thank you so much!

**Comment by oezyurty** [comment]
Hi, thank you so much for all the kind words! It's my pleasure to see your interest in our work! 

Let me briefly answer your questions: 

1. I think it looks alright. Only for `mortality.npy` I am not sure whether it was `N` or `N*1`. If the first one doesn't work, please try the second alternative. 
2. Yes, you can run the code without using mask. You can see in our code that we take `use_mask` as a boolean input. If you specify as false, the code will not use the mask during training or inference. **One quick note:** The current version of the code may still require you to provide the mask as an input (although not used later on). If that's the case, as a quick hack, you can trivially create your mask with full of 1s, with the same shape of timeseries. Then by setting `use_mask=False`, you can ensure that this mask is not used. 

I hope these clarifications help your project. 

My best wishes!

**Comment by xinyuejohn** [comment]
Thanks for your prompt and detailed reply!

**Comment by xinyuejohn** [comment]
@oezyurty Thanks for your guidance; your model significantly impacted my master thesis project. Could I include the CLUDA framework figure from your paper in my master's thesis? It will be used strictly for academic purposes, won't be published or made publicly available, and I will cite your work properly.

**Comment by oezyurty** [comment]
Sure! As long as you correctly cite our work also for the caption of the figure, you can use our figure in your thesis :)
